const PLAYER_COMMAND_NAMES = [
  'help',
  'balance',
  'beg',
  'buy',
  'crime',
  'daily',
  'deposit',
  'eleaderboard',
  'fish',
  'gamble',
  'inventory',
  'mine',
  'pay',
  'rob',
  'shop',
  'slut',
  'withdraw',
  'work',
  'count',
  'fight',
  'flip',
  'roll',
  'join',
  'music',
  'nowplaying',
  'play',
  'queue',
  'search',
  'baseconvert',
  'calculate',
  'countdown',
  'hexcolor',
  'poll',
  'randomuser',
  'shorten',
  'time',
  'unixtime',
  'avatar',
  'todo',
  'weather',
  'report',
  'reports',
];

export const PLAYER_COMMANDS = new Set(PLAYER_COMMAND_NAMES);

export function isPlayerCommand(commandName) {
  return PLAYER_COMMANDS.has(String(commandName || '').toLowerCase());
}
